#!/usr/bin/ksh

#	Step #1 - Set QMgr and Clear Data Files
y=$(ps -ef | grep runmqlsr | grep -v 'grep'| awk '{ print $15 }')

echo 'export MQSERVER='\''TEST/TCP/'`hostname`'('${y}')'\' > exportmqport

chmod 775 exportmqport

. ./exportmqport

y=$(ps -ef | grep runmqlsr | grep -v 'grep'| awk '{ print $11 }')
dspmq
echo "Choose which QM to work with"
IFS="
"
select x in $(dspmq |awk '{print $1}' | sed -e "s/.*(//g" -e "s/).*//g")
do
MENU_QM=${x}
break
done
	QMGR=$MENU_QM

	for i in aliasq-d localq-d   remoteq-d  svrconn-d  xmitq-d allchan-d
	do
		cp /dev/null ${i}
	done


#	Step #2 - Collect localq, xmitq, remoteq & svrconn data

	echo "dis ql(*) where(usage ne xmitq)" | runmqsc ${QMGR} | grep QUEUE | grep -v SYSTEM | grep -v MQMGM | grep -v NASTEL | grep -v MQCONTROL | grep -v CITI.DLQ | grep -v PUBSUB.DLQ  > localq-d
 	echo "dis ql(*) where(usage eq xmitq)" | runmqsc ${QMGR} | grep QUEUE | grep -v SYSTEM > xmitq-d
 	echo "dis qr(*)" | runmqsc ${QMGR} | grep QUEUE | grep -v SYSTEM > remoteq-d
 	echo "dis qa(*)" | runmqsc ${QMGR} | grep QUEUE | grep -v SYSTEM > aliasq-d
	echo "dis chl(*) where(chltype eq svrconn)" | runmqsc ${QMGR} | grep CHANNEL | grep -v SYSTEM > svrconn-d

	echo "dis chl(*)" | runmqsc ${QMGR} | grep CHANNEL | grep -v SYSTEM > allchan-d
exit 0
