#!/usr/bin/ksh
echo
let "myrand=RANDOM%(37-32+1)+32"
#echo $myrand
printf '\033[1;'${myrand}';40m '
cal
date
echo
printf '\033[1;33;41m '"******************** W A R N I N G *******************  THIS MENU will do STOP and START FUNCTIONS  ************ USE EXTREME CAUTION ************"
#echo "******************** W A R N I N G *******************  THIS MENU will do STOP and START FUNCTIONS  ************ USE EXTREME CAUTION ************";
printf '\033[1;'${myrand}';40m '
echo
echo "PLEASE NOTE:  You can do a control-c at anytime to break out of this menu or any script during execution"
echo
echo "Hostname: " `hostname`
echo
echo '======================================================================================================='
echo
echo '  MQ Queue Manager                                         Current Status'
echo
dspmq
echo
printf '\033[0m'
SCRIPTDIR="/net/mqclus1/export/zones/mqclz1/root/export/opt/mqsupport/setup_7.0_Solaris_M7/testscripts"
IFS="
"
select x in $(cat /net/mqclus1/export/zones/mqclz1/root/export/opt/mqsupport/setup_7.0_Solaris_M7/testscripts/menu1.lst) exit
do
#echo off  
cd /net/mqclus1/export/zones/mqclz1/root/export/opt/mqsupport/setup_7.0_Solaris_M7/testscripts
#echo on
if [[ $x = "exit" ]];then
   exit
else
   . /net/mqclus1/export/zones/mqclz1/root/export/opt/mqsupport/setup_7.0_Solaris_M7/testscripts/$x
fi
#. /net/mqclus1/export/zones/mqclz1/root/export/opt/mqsupport/setup_7.0_Solaris_M7/testscripts/$x
break
done
echo "************* Script Execution Done *************** Ctrl C to quit before clear screen **************"
read nothing
echo `clear`
. ./menu1
